version: '3.7'
services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 8088:80
    depends_on:
      - web
  web:
    container_name: dev_backend
    build: .
    restart: on-failure
    env_file: dev.env
    command: gunicorn core.wsgi --bind 0.0.0.0:5000
    volumes:
     - .:/app
     - static_volume:/app/static
    ports:
      - 5000:5000
    depends_on:
     - db
  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    env_file: dev.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: homescript1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: cocody
    restart: always

volumes:
  static_volume:
  postgres_data:
